"""add medical_records xray_images ai_analysis_results tables

Revision ID: 140cb98c82af
Revises: cf5162ec21d6
Create Date: 2026-06-06 19:41:58.971255

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '140cb98c82af'
down_revision: Union[str, Sequence[str], None] = 'cf5162ec21d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
